name: ❓ Question Support
description: Ask a question related to the project
labels: ["kind/question", "status/triage"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Provide a clear and concise description of the question you're asking. Include any context that will help us understand the issue.
    validations:
      required: true
  - type: input
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce (if applicable)
      description: |
        If your question is related to a bug or unexpected behavior, provide the steps to reproduce the issue.
    validations:
      required: false
  - type: textarea
    id: expected_outcome
    attributes:
      label: Expected Outcome
      description: |
        What did you expect to happen?
    validations:
      required: false
  - type: textarea
    id: actual_outcome
    attributes:
      label: Actual Outcome
      description: |
        What actually happened? Be as specific as possible.
    validations:
      required: false
  - type: input
    id: discussion
    attributes:
      label: Discussion Link (optional)
      description: |
        If this question has already been discussed or answered in the GitHub Discussions, provide a link to the discussion.
    validations:
      required: false
  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: |
        Any other context that might be helpful for us to know in answering your question.
    validations:
      required: false
